# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-01 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactManagerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='MobileNo',
            field=models.IntegerField(null=True),
        ),
    ]
