# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-01 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactManagerApp', '0003_remove_contact_lastmodifieddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='MobileNo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
