# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-01 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactManagerApp', '0004_auto_20170701_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='FirstName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
