# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-01 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactManagerApp', '0006_auto_20170701_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='FirstName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='MobileNo',
            field=models.IntegerField(max_length=12, null=True),
        ),
    ]
