# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-06 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactManagerApp', '0007_auto_20170701_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='FirstName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='LastName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='MobileNo',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
